### ISSUE TITLE
trying  to use it and breaks literally every step of the way

### ISSUE THREAD

**Issue by berlinguyinca** [rosdyana/Going-Deeper-with-Convolutional-Neural-Network-for-Stock-Market-Prediction#3]
would it be possible to get a complete example? I keep running in all kind of issues, from keras warnings, over methods not found errors, missing requirements, etc.

example:

/home/wohlgemuth/workspace/Going-Deeper-with-Convolutional-Neural-Network-for-Stock-Market-Prediction/venv/bin/python /home/wohlgemuth/workspace/Going-Deeper-with-Convolutional-Neural-Network-for-Stock-Market-Prediction/myDeepCNN.py -i dataset/20_50/2880.TW -e 50 -d 50 -b 8 -o outputresult.txt
2019-06-19 05:39:27.101687: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2019-06-19 05:39:27.126885: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2112000000 Hz
2019-06-19 05:39:27.127344: I tensorflow/compiler/xla/service/service.cc:150] XLA service 0x1c1c450 executing computations on platform Host. Devices:
2019-06-19 05:39:27.127362: I tensorflow/compiler/xla/service/service.cc:158]   StreamExecutor device (0): <undefined>, <undefined>
Using TensorFlow backend.
loading dataset
train size : 3751
train size : 331
/home/wohlgemuth/workspace/Going-Deeper-with-Convolutional-Neural-Network-for-Stock-Market-Prediction/myDeepCNN.py:55: UserWarning: Update your `Conv2D` call to the Keras 2 API: `Conv2D(32, (3, 3), activation="relu", padding="same", kernel_initializer="glorot_uniform")`
number of classes : 331
  border_mode='same', activation='relu')(input_layer)
WARNING:tensorflow:From /home/wohlgemuth/workspace/Going-Deeper-with-Convolutional-Neural-Network-for-Stock-Market-Prediction/venv/lib/python3.7/site-packages/tensorflow/python/framework/op_def_library.py:263: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
Instructions for updating:
Colocations handled automatically by placer.
/home/wohlgemuth/workspace/Going-Deeper-with-Convolutional-Neural-Network-for-Stock-Market-Prediction/myDeepCNN.py:61: UserWarning: Update your `Conv2D` call to the Keras 2 API: `Conv2D(48, (3, 3), activation="relu", padding="same", kernel_initializer="glorot_uniform")`
  activation='relu')(x)
WARNING:tensorflow:From /home/wohlgemuth/workspace/Going-Deeper-with-Convolutional-Neural-Network-for-Stock-Market-Prediction/venv/lib/python3.7/site-packages/keras/backend/tensorflow_backend.py:3445: calling dropout (from tensorflow.python.ops.nn_ops) with keep_prob is deprecated and will be removed in a future version.
Instructions for updating:
Please use `rate` instead of `keep_prob`. Rate should be set to `rate = 1 - keep_prob`.
/home/wohlgemuth/workspace/Going-Deeper-with-Convolutional-Neural-Network-for-Stock-Market-Prediction/myDeepCNN.py:68: UserWarning: Update your `Conv2D` call to the Keras 2 API: `Conv2D(64, (3, 3), activation="relu", padding="same", kernel_initializer="glorot_uniform")`
  activation='relu')(x)
/home/wohlgemuth/workspace/Going-Deeper-with-Convolutional-Neural-Network-for-Stock-Market-Prediction/myDeepCNN.py:74: UserWarning: Update your `Conv2D` call to the Keras 2 API: `Conv2D(96, (3, 3), activation="relu", padding="same", kernel_initializer="glorot_uniform")`
  activation='relu')(x)
/home/wohlgemuth/workspace/Going-Deeper-with-Convolutional-Neural-Network-for-Stock-Market-Prediction/myDeepCNN.py:84: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", units=256)`
  x = Dense(output_dim=256, activation='relu')(x)
/home/wohlgemuth/workspace/Going-Deeper-with-Convolutional-Neural-Network-for-Stock-Market-Prediction/myDeepCNN.py:88: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="softmax", units=2)`
  x = Dense(output_dim=2, activation='softmax')(x)
Traceback (most recent call last):
  File "/home/wohlgemuth/workspace/Going-Deeper-with-Convolutional-Neural-Network-for-Stock-Market-Prediction/myDeepCNN.py", line 195, in <module>
    main()
  File "/home/wohlgemuth/workspace/Going-Deeper-with-Convolutional-Neural-Network-for-Stock-Market-Prediction/myDeepCNN.py", line 137, in main
    model.fit(X_train, Y_train, batch_size=batch_size, epochs=epochs)
  File "/home/wohlgemuth/workspace/Going-Deeper-with-Convolutional-Neural-Network-for-Stock-Market-Prediction/venv/lib/python3.7/site-packages/keras/engine/training.py", line 952, in fit
    batch_size=batch_size)
  File "/home/wohlgemuth/workspace/Going-Deeper-with-Convolutional-Neural-Network-for-Stock-Market-Prediction/venv/lib/python3.7/site-packages/keras/engine/training.py", line 751, in _standardize_user_data
    exception_prefix='input')
  File "/home/wohlgemuth/workspace/Going-Deeper-with-Convolutional-Neural-Network-for-Stock-Market-Prediction/venv/lib/python3.7/site-packages/keras/engine/training_utils.py", line 128, in standardize_input_data
    'with shape ' + str(data_shape))
ValueError: Error when checking input: expected input_1 to have 4 dimensions, but got array with shape (3751, 7500)

**Comment by tondatto** [comment]
That error is because the project is using `util/dataset_traditional.py` instead `util/dataset.py`. 

I fix it by comment these lines in `utils/__init__.py`

```
from __future__ import absolute_import
from . import dataset
# from . import dataset_traditional

from .dataset import dataset
# from .dataset_traditional import dataset
```
